services:
  apache:
    image: httpd:2.4
    container_name: gateway-apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/conf:/usr/local/apache2/conf
      - ./apache/html:/usr/local/apache2/htdocs
    restart: always

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: gateway-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana-oss:11.0.0
    container_name: gateway-grafana
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: always

volumes:
  prometheus_data:
  grafana_data: